### ISSUE TITLE
does not detect other files in the folder

### ISSUE THREAD

**Issue by dimitrijedimaa** [amakvana/Bat-2-Exec#2]
what directory does it run in? temp?

**Comment by amakvana** [comment]
The way `IEXPRESS` works is that it copies the bat script into a folder located in `%TEMP%\IXP000.TMP\` and then executes it within that directory. Once the script is completed, the folder is then deleted by itself.

So what you can do is hard-code the paths to other files, but ensure they do not exist inside the `IXP000.TMP` folder 

See [HERE](https://stackoverflow.com/a/13713000) and [HERE](https://stackoverflow.com/a/13698019) for a thorough explanation.

**Comment by dimitrijedimaa** [comment]
thank you
