### ISSUE TITLE
the generated exe file does not support command line argument 

### ISSUE THREAD

**Issue by mikekgr** [amakvana/Bat-2-Exec#4]
Hello,
this Bat-2-Exec converter is very promising and thanks for make it for us.
I found a critical (for my needs) problem: it doesn't support command line argument e.g. my-script.exe /h  
Can you consider to implement this vital feature to me?
Thanks

**Comment by amakvana** [comment]
Apologies for the delayed reply! 

You need to manually override the default install command. Using `my-script.exe` as the name of the generated executable, try this:

````
my-script.exe /c:"cmd /c my-script.bat /h"
````

**Comment by mikekgr** [comment]
> Apologies for the delayed reply!
> 
> You need to manually override the default install command. Using `my-script.exe` as the name of the generated executable, try this:
> 
> ```
> my-script.exe /c:"cmd /c my-script.bat /h"
> ```

Many thanks @amakvana  this way is working as it should !!!

**Comment by amakvana** [comment]
Glad to hear it's all working as expected! I'm closing the issue now.
